version: '3'
services:
  backend:
    volumes:
      - ./data:/app/upload
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 172.25.112.4
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: TY%pwd123
      DB_NAME: xxl_job
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    command: ["dockerize", "-wait", "tcp://backend:8000", "-timeout", "60s", "--", "npm", "run", "dev"]
volumes:
  db_data: