version: '3'
services:
  web-mysql:
    hostname: web-mysql
    image: mysql:5.7
    environment:
      # MYSQL_HOST: localhost
      # MYSQL_PORT: 3306
      # MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: TY%pwd123
      MYSQL_DATABASE: xxl_job
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    command: ["./wait-for-db.sh", "web-mysql", "--", "./init.sh"]
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      DB_HOST: web-mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: TY%pwd123
      DB_NAME: xxl_job
    depends_on:
      - web-mysql
  frontend:
    command: ["./wait-for-backend.sh", "backend", "--", "npm", "run", "dev"]
    build:
      context:  ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  db_data: